### PR TITLE
Run tests only on major releases

### PR DESCRIPTION
**Pull request by john-dupuy**
There's a bug that's impacting the plugin install test:
```
FAIL: Plugin install, load, unload, and uninstall failed with the following:
Traceback (most recent call last):
  File "<string>", line 73, in <module>
  File "/usr/share/qgis/python/pyplugin_installer/installer.py", line 581, in installFromZipFile
    QgsSettings.createPluginTreeNode("_plugin_manager").childSetting("last-zip-directory").setValue(QFileInfo(filePath).absoluteDir().absolutePath())
AttributeError: 'NoneType' object has no attribute 'setValue'
```

I believe it may have come from https://github.com/qgis/QGIS/pull/51614? Regardless, we should only run tests and install against the stable releases.

### CODE REVIEW

**Comment by john-dupuy** [comment]
@Samweli  I see you just did a release of the plugin - please update the changelog in `planet_explorer/metadata.txt` whenever you do a release.

It will resolve this test failure error:
```
    def test_changelog_up_to_date(request):
        """
        Verifies:
            - PLQGIS-TC19
        """
        root_dir = request.config.rootdir
        if root_dir.basename == "tests":
            root_dir = root_dir / ".." / ".."
        most_recent_release_on_github = requests.get(
            urljoin(REPO_URL, "releases?per_page=1")
        ).json()[0]["name"]
        most_recent_release_in_changelog = get_recent_release_from_changelog(root_dir)
>       assert (
            most_recent_release_in_changelog == most_recent_release_on_github
        ), "Release on Github does not match the most recent changelog entry!"
E       AssertionError: Release on Github does not match the most recent changelog entry!
E       assert 'v2.2.0' == 'v2.3.0'
E         - v2.3.0
E         ?    ^
E         + v2.2.0
```

**Comment by Samweli** [comment]
> @Samweli I see you just did a release of the plugin - please update the changelog in `planet_explorer/metadata.txt` whenever you do a release.
> 
> It will resolve this test failure:

@john-dupuy thanks,It is not an officiall release I was testing to see if the new custom plugin repository changes are in effect.

**Comment by john-dupuy** [comment]
> > @Samweli I see you just did a release of the plugin - please update the changelog in `planet_explorer/metadata.txt` whenever you do a release.
> > It will resolve this test failure:
> 
> @john-dupuy thanks,It is not an official release I was testing to see if the new custom plugin repository changes are in effect.

Thanks @Samweli, not a huge issue. I suggest setting future non-official releases to a pre-release (`non-production` ready).

**Comment by Samweli** [comment]
> Thanks @Samweli, not a huge issue. I suggest setting future non-official releases to a pre-release (`non-production` ready).

Sure, thanks. I have removed the release and the related tag, will update them after I have made changes in the metadata file.

**Pull request merged**
