### PR TITLE
set proxy info in dispatcher

### PR DESCRIPTION
**Pull request by volaya**

### CODE REVIEW

**Comment by ischneider** [comment]
One small issue (I think):

Seems like the configuration for requests should contain a key for both http and https.

Otherwise looks like the right approach to me. 

Other thoughts:

- If socks was configured, it seems like requests can handle this? https://requests.readthedocs.io/en/master/user/advanced/#socks
- As noted earlier, it could be possible there is some other proxy type configured (the FTP one?) maybe we should notify/handle this?
- Re: the possibility of having `No proxy for` rules in place, I suppose grabbing this configuration value and then manually implementing this functionality via the dispatcher could be possible.

**Comment by mirandadam** [comment]
Thanks for the quick turnaround. @ischneider has a point. For correctness and completeness sake, it would be best to read and consider all the options provided by QGis, namely the no-proxy rules in the "No proxy for (URLs starting with)" window. Otherwise the bug would technically still be there, although it would only be triggered by a very specific use case:
Say that I request for a passthrough rule for Planet's API to my IT department, but a proxy is still required to access some other dataset. I would configure QGis' proxy, but would list planet's api endpoint in the no_proxy rules.

**Comment by volaya** [comment]
see https://github.com/planetlabs/qgis-planet-plugin/pull/8

**Comment by mirandadam** [comment]
Awesome! Thanks!

**Pull request merged**
