### PR TITLE
Preparation for v2.3.0 pre release

### PR DESCRIPTION
**Pull request by Samweli**
Updates the metadata.txt with the new pre-release details

Highlight of the changes that will be included in the new release
- Fixed the auto-fill coordinates feature for setting a point collect location in QGIS and auto-populating those coordinates to our tasking dashboard - https://github.com/planetlabs/qgis-planet-plugin/pull/70
- Added STAC metadata as a checkout option so that users can download their data with STAC metadata - https://github.com/planetlabs/qgis-planet-plugin/pull/67
-  New "add to map" button in the Orders Panel, that when used will automatically order our spectral bands to the right RGB display for PlanetScope and SkySat - https://github.com/planetlabs/qgis-planet-plugin/pull/103
-  Added a sqkm size estimate when drawing an area to download Basemap Quads - https://github.com/planetlabs/qgis-planet-plugin/pull/69
- Customers can now search within their multi-polygons -https://github.com/planetlabs/qgis-planet-plugin/pull/94
- Better bug handling and tracking with Sentry -https://github.com/planetlabs/qgis-planet-plugin/pull/75 and https://github.com/planetlabs/qgis-planet-plugin/pull/80
- Basemaps cadences are now listed in the correct order -https://github.com/planetlabs/qgis-planet-plugin/pull/92
- Fix for area coverage filtering - https://github.com/planetlabs/qgis-planet-plugin/pull/119
- Fixed some the metadata fields in the imagery footprints -https://github.com/planetlabs/qgis-planet-plugin/pull/98

### CODE REVIEW

**Comment by Samweli** [comment]
@john-dupuy I wasn't expecting to have this error https://github.com/planetlabs/qgis-planet-plugin/actions/runs/4058641912/jobs/6985801191

**Comment by john-dupuy** [comment]
> @john-dupuy I wasn't expecting to have this error https://github.com/planetlabs/qgis-planet-plugin/actions/runs/4058641912/jobs/6985801191

I believe this test has a chicken and egg problem :disappointed: - it's expecting the changelog entry to match the current release on github but the changelog entry needs to come before the github release. In any case, we should update the text in this PR to reflect the changes coming in `v2.3.0`, merge this in, and then do the github release.

**Comment by Samweli** [comment]
> > @john-dupuy I wasn't expecting to have this error https://github.com/planetlabs/qgis-planet-plugin/actions/runs/4058641912/jobs/6985801191
> 
> I believe this test has a chicken and egg problem :disappointed: - it's expecting the changelog entry to match the current release on github but the changelog entry needs to come before the github release. In any case, we should update the text in this PR to reflect the changes coming in `v2.3.0`, merge this in, and then do the github release. 
> 
> Then that test should pass on master. 

Sure, I'm going to update this PR with the changelog changes text then will let you know, thanks.

**Comment by Samweli** [comment]
@john-dupuy I have update the PR description and the plugin metadata changelog. thanks

**Review by john-dupuy — APPROVED** [review]

**Pull request merged**
